version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  web:
    image: vetttta06/library-web:latest
    environment:
      DB_HOST: db
      DB_NAME: library_db
      DB_USER: library_user
      DB_PASSWORD: secure_password
      SECRET_KEY: "django-insecure-ra+$$gw#tqc#=5bcd+fj34mvf50y8xqr!k2&nd5o^!vo-d66$$ar"
      PORT: 8000
    networks:
      - library-network
    volumes:
      - static_volume:/app/staticfiles
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  nginx:
    image: vetttta06/library-nginx:latest
    ports:
      - "80:80"
    networks:
      - library-network
    volumes:
      - static_volume:/app/staticfiles
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - web

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - library-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  metabase:
    image: metabase/metabase:latest
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: library_db
      MB_DB_HOST: db
      MB_DB_PORT: 5432
      MB_DB_USER: library_user
      MB_DB_PASS: secure_password
      MB_SITE_NAME: "Library Analytics"
      MB_ANONYMOUS_TRACKING_ENABLED: "false"
    networks:
      - library-network
    volumes:
      - metabase_data:/metabase-data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.metabase.rule=Host(`localhost`) && PathPrefix(`/analytics/`)"
        - "traefik.http.services.metabase.loadbalancer.server.port=3000"

volumes:
  postgres_data:
    external: true
    name: library_postgres_data
  redis_data:
    external: true
    name: library_redis_data
  static_volume:
    external: true
    name: library_static_volume
  metabase_data:
    external: true
    name: library_metabase_data

networks:
  library-network:
    driver: overlay
    attachable: true